### ISSUE TITLE
How to train a model on my own dataset?

### ISSUE THREAD

**Issue by brisker** [bernard24/RIS#1]
How to train a model using recurrent networks on my own dataset?

**Comment by bernard24** [comment]
In order to train with any dataset, you can start from the experiment in the plants_learning directory. When running an experiment (e.g. see launcher.sh) you can specify the flag -data_dir <your_dataset> to specify where your dataset is. Within that directory you should have all input and ground truth images, as well as two text files:
data_list.txt: containing in each line the name of a training input image.
label_list.txt: containing in each line the name of the ground truth image in the same order as in data_list.txt.

Depending on your data, you may also need to specify the size of your input with the flags -height and -width, and maybe tinker with the structure of the net to achieve better results (e.g. modifying the FCN in create_cnn.lua).

**Comment by brisker** [comment]
@bernard24 
Could you please give a demo showing how to train on the  leaf-segmentation dataset?

**Comment by bernard24** [comment]
You can run the script: plants_learning/launcher.sh. Within the script, you can specify the -data_dir flag, pointing to where your dataset is (the txt files mentioned in the previous answer should be in that directory too).
Regarding the plants leaves dataset, you can get it from [http://www.plant-phenotyping.org/CVPPP2014-dataset](http://www.plant-phenotyping.org/CVPPP2014-dataset).

**Comment by brisker** [comment]
@bernard24 
Help
I have done the preparation work , put the   cvppp dataset in the right format in the data folder, but after I run the launcher.sh , I got this error:

[program started on Thu Oct 20 18:56:02 2016]  
[command line arguments]  
........
data_dir    ../Data/LSCData/A1/ 
[----------------------]  
Creating CNN model from scratch.  
Creating ConvLSTM model from scratch.  
Is it big? 1  
cloning rnn 
cloning post_lstm  
Starting training...  
number of parameters in the model: 473343  
~/torch/install/bin/luajit: inconsistent tensor size at  ~/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:7
stack traceback:
    [C]: at 0x7f7115a75580
    [C]: in function 'reshape'
    ./plants_utils.lua:84: in function 'create_instance'
    experiment.lua:243: in main chunk
    [C]: in function 'dofile'
    ...code/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

@bernard24

**Comment by brisker** [comment]
@bernard24

**Comment by bernard24** [comment]
This is probably because the code is expecting the ground truth to be a 1-channel image in which each pixel should contain a number indicating the instance to which that object belongs to.
I have added a short matlab script which transform the plants ground truth images into that format.

**Comment by brisker** [comment]
Thanks @bernard24 
Besides, 
Is CRF method included in the code? If included, where?

**Comment by bernard24** [comment]
The CRF is not included here, as it is not used at training time, only as a post-processing. If you want to apply it, you have an implementation of it at [http://graphics.stanford.edu/projects/densecrf](http://graphics.stanford.edu/projects/densecrf).

**Comment by isn4** [comment]
@bernard24 Hi, how come the people_learning experiment.lua doesn't have the same set of command line options?
Also, since it doesn't have "-data_dir" (instead it has "-images_dir" and "-labels_dir") shall I put the txt files with the paths to each image in their respective files (label_list.txt in labels_dir)?
And is there a way for me to specify height and width since the people_learning experiment.lua doesn't have "-height" and "-width" command line arguments?

**Comment by bernard24** [comment]
@isn4 yes that is right.
About the height and width, in the people experiment I am assuming that images have the same height and width, and it is defined in https://github.com/bernard24/RIS/blob/master/people_learning/experiment.lua line 71, variable side_size, so you can directly change the value of that variable. You will have to change a bit more of the code, basically in the function createInstance, to differentiate between height and width and specify a value for each of them.

**Comment by isn4** [comment]
@bernard24 Thank you!
I've got the model running after making some of the tweaks you suggested.
