### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by xjoshramos** [bernard24/RIS#5]
How to implement inference?

**Comment by xjoshramos** [comment]
th infer_example.lua?

**Comment by isn4** [comment]
Hi @bernard24 and @xjoshramos , should we be using 'plants_convlstm.model' or 'plants_pre_lstm.model' in line 34 of infer_example.lua (`x = model:forward(input)`)? I'm getting this error when I try to use either:
_unknown Torch class <torch.CudaTensor>_
The variable 'model' doesn't seem to be defined in this particular inference script I assume so that users can pick whichever model they please.

**Comment by isn4** [comment]
Hi @bernard24 & @xjoshramos , I have added some missing modules, require 'cunn' and 'cudnn', which has fixed the above mentioned error. However, while I'm able to torch.load() either 'plants_convlstm.model' or 'plants_pre_lstm.model' and able to print their contents (ie, they are not nil) they do not respond to the forward() command. Is there another way I have to read in a model?
I have opened a new issue addressing this.
